# 基础镜像
FROM redis
# author
MAINTAINER pdfutil

# 挂载目录
VOLUME /home/pdfutil/redis
# 创建目录
RUN mkdir -p /home/pdfutil/redis
# 指定路径
WORKDIR /home/pdfutil/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/pdfutil/redis/redis.conf
